name = "homebrew"
description = "适用于macOS的包管理器。它使您能够从命令行安装和更新软件包，从而使您的Mac保持最新状态，而无需使用App Store。"
dependencies = []

[[install_tasks]]
[install_tasks.DownloadTask]
url = "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
dest = "{{TEMP_DIR}}/homebrew/install.sh"

[[install_tasks]]
[install_tasks.CommandTask]
script = "{{TEMP_DIR}}/homebrew/install.sh"
envs = [["NONINTERACTIVE", "1"]]
shell = "macos_sudo"

[[uninstall_tasks]]
[uninstall_tasks.DownloadTask]
url = "https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh"
dest = "{{TEMP_DIR}}/homebrew/uninstall.sh"

[[uninstall_tasks]]
[uninstall_tasks.CommandTask]
script = "{{TEMP_DIR}}/homebrew/uninstall.sh"
envs = [["NONINTERACTIVE", "1"]]
shell = "macos_sudo"

[[check_tasks]]
[check_tasks.WhichTask]
command = "brew"
