name = "cargo"
description = "Rust's 包管理器"
dependencies = []

[[install_tasks]]
[install_tasks.DownloadTask]
url = "https://sh.rustup.rs"
dest = "{{TEMP_DIR}}/rustup/rustup-init.sh"

[[install_tasks]]
[install_tasks.CommandTask]
script = "{{TEMP_DIR}}/rustup/rustup-init.sh"
args = ["--profile", "complete", "-y"]
shell = "bash"

[[uninstall_tasks]]
[uninstall_tasks.CommandTask]
script = "rustup self uninstall"
args = []
shell = "bash"

[[check_tasks]]
[check_tasks.WhichTask]
command = "rustup"
