name = "bat"
description = "具有语法高亮的cat替代品"
dependencies = ["cargo"]

[[install_tasks]]
[install_tasks.InstallTask]
installer = "cargo"
name = "bat"

[[uninstall_tasks]]
[uninstall_tasks.UninstallTask]
installer = "cargo"
name = "bat"

[[check_tasks]]
[check_tasks.CheckTask]
installer = "cargo"
name = "bat"
