name = "cargo-xcode"
description = "cargo子命令用于生成xcode project"
dependencies = ["cargo"]

[[install_tasks]]
[install_tasks.InstallTask]
installer = "cargo"
name = "cargo-xcode"

[[uninstall_tasks]]
[uninstall_tasks.UninstallTask]
installer = "cargo"
name = "cargo-xcode"

[[check_tasks]]
[check_tasks.CheckTask]
name = "cargo-xcode"
installer = "cargo"
