name = "exa"
description = "具有颜色高亮的ls替代品"
dependencies = ["cargo"]

[[install_tasks]]
[install_tasks.InstallTask]
installer = "cargo"
name = "exa"

[[uninstall_tasks]]
[uninstall_tasks.UninstallTask]
installer = "cargo"
name = "exa"

[[check_tasks]]
[check_tasks.CheckTask]
installer = "cargo"
name = "exa"
