name = "flutter"
description = "一个UI框架"
dependencies = ["brew"]

[[install_tasks]]
[install_tasks.InstallTask]
installer = "brew"
name = "flutter"

[[uninstall_tasks]]
[uninstall_tasks.UninstallTask]
installer = "brew"
name = "flutter"

[[check_tasks]]
[check_tasks.WhichTask]
command = "flutter"
